// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-program-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var INFO = {
  nome: "Mentoria RP3 \u2014 Chordata Consultoria",
  metodo: "M\xE9todo RP3 (Processos, Pessoas e Planejamento)",
  publico: "Gestores, s\xF3cios e l\xEDderes de cl\xEDnicas e hospitais veterin\xE1rios",
  turma: "Junho 2026",
  formato: "Turmas reduzidas, mentoria em grupo + individual, diagn\xF3stico gratuito",
  valorBRL: 2300,
  parcelamento: "Pix ou Boleto \xE0 vista, ou Cart\xE3o em at\xE9 6x sem juros",
  inscricoesUrl: "https://mentoria-rp3.lovable.app/#investimento",
  site: "https://mentoria-rp3.lovable.app"
};
var get_program_info_default = defineTool({
  name: "get_program_info",
  title: "Informa\xE7\xF5es da Mentoria RP3",
  description: "Retorna informa\xE7\xF5es institucionais do programa Mentoria RP3: m\xE9todo, p\xFAblico-alvo, turma vigente, formato, valor e link de inscri\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/tools/validate-coupon.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var VALOR_TOTAL = 2300;
var validate_coupon_default = defineTool2({
  name: "validate_coupon",
  title: "Validar cupom de desconto",
  description: "Valida um c\xF3digo de cupom da Mentoria RP3 e retorna se est\xE1 ativo, o percentual de desconto e o valor final da inscri\xE7\xE3o.",
  inputSchema: {
    codigo: z.string().trim().min(1).max(60).describe("C\xF3digo do cupom (ex: TESTE100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ codigo }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    const code = codigo.toUpperCase();
    const res = await fetch(
      `${supabaseUrl}/rest/v1/cupons_rp3?codigo=eq.${encodeURIComponent(code)}&select=*`,
      {
        headers: {
          apikey: serviceKey,
          Authorization: `Bearer ${serviceKey}`
        }
      }
    );
    if (!res.ok) {
      return { content: [{ type: "text", text: `Erro ao consultar cupom (${res.status}).` }], isError: true };
    }
    const rows = await res.json();
    const cupom = rows[0];
    let resultado;
    if (!cupom || !cupom.ativo) {
      resultado = { valido: false, error: "Cupom n\xE3o encontrado." };
    } else if (cupom.expira_em && new Date(cupom.expira_em).getTime() < Date.now()) {
      resultado = { valido: false, error: "Cupom expirado." };
    } else if (cupom.max_usos != null && cupom.usos >= cupom.max_usos) {
      resultado = { valido: false, error: "Cupom esgotado." };
    } else {
      const percentual = Number(cupom.percentual_desconto);
      const valorFinal = Math.max(0, Math.round(VALOR_TOTAL * (1 - percentual / 100) * 100) / 100);
      resultado = {
        valido: true,
        codigo: code,
        percentual,
        valorOriginal: VALOR_TOTAL,
        valorFinal,
        gratuito: valorFinal === 0
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(resultado, null, 2) }],
      structuredContent: resultado
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mentoria-rp3-mcp",
  title: "Mentoria RP3 \u2014 Chordata",
  version: "0.1.0",
  instructions: "Ferramentas do site da Mentoria RP3 (Chordata Consultoria). Use `get_program_info` para consultar dados do programa (m\xE9todo, valor, turma, inscri\xE7\xE3o) e `validate_coupon` para validar c\xF3digos de cupom de desconto.",
  tools: [get_program_info_default, validate_coupon_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
